# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7de9cc95f84693811607129588c6f98876287fd3e1232027b0771ff0ee316a2fd1c6c26be7d785194ab7a7c491cb97040c342cd6f17aec5d03961932a0ff7e5b

test:
  secret_key_base: 9cbc01c154d823aa64b513267da76667f6ddf394aa54e610e93c9236ce8185ba151ed7b565bd885775fdb37eebda0d62bdaa0d64538ddfa0db7020cfcb22cf7e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
